<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use Inertia\Inertia;

class EggReceiveAndGradingReportController extends Controller
{
    /**
     * Display the Egg Receive & Grading Report page.
     */
    public function index()
    {
        // Report metadata
        $reportData = [
            'report_title' => 'Egg Received and Grading Report Of Farm- PHL-1',
            'received_date' => '24.05.2025',
            'he_pro_date' => '22.23.05.2025',
            'report_no' => '285',
            'stock_day_before_set' => '6',
            'unloading_time_start' => '9.00.Am',
            'unloading_time_finish' => '9.30.Am',
            'total_time_elapsed_unloading' => '0.30',
            'driver_name' => 'Sujon',
            'vehicle_no' => '12-1161',
            'mobile_no' => '1865972468',
            'unloading_sup_name' => 'Shahabuddin',
            'challan_no' => '3936',
            'egg_grading_date' => '24.05.2025',
            'grading_start_time' => '3.00.Am',
            'grading_finish_time' => '6.00.Pm',
            'total_time_elapsed_grading' => '3.00',
        ];

        // Sample data matching the image structure
        $sheds = [
            [
                'shed_no' => '4',
                'flocks' => [
                    [
                        'flock_no' => '4',
                        'breed' => 'MC',
                        'age_wks' => '77.4',
                        'pro_date' => '23.05',
                        'received_egg' => 1800,
                        'commercial' => 0,
                        'broken' => 4,
                        'liquid' => 2,
                        'damage' => 6,
                        'total_reject' => 12,
                        'reject_percent' => 0.67,
                        'hatchable_egg' => 1788,
                        'total_hatchable' => 1788,
                        'set_egg_qty1' => 1788,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '5',
                        'breed' => 'MC',
                        'age_wks' => '76.1',
                        'pro_date' => '24.05',
                        'received_egg' => 2100,
                        'commercial' => 0,
                        'broken' => 6,
                        'liquid' => 3,
                        'damage' => 7,
                        'total_reject' => 16,
                        'reject_percent' => 0.76,
                        'hatchable_egg' => 2084,
                        'total_hatchable' => 2084,
                        'set_egg_qty1' => 2084,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '6',
                        'breed' => 'MC',
                        'age_wks' => '75.3',
                        'pro_date' => '25.05',
                        'received_egg' => 2020,
                        'commercial' => 0,
                        'broken' => 5,
                        'liquid' => 2,
                        'damage' => 4,
                        'total_reject' => 11,
                        'reject_percent' => 0.54,
                        'hatchable_egg' => 2009,
                        'total_hatchable' => 2009,
                        'set_egg_qty1' => 2009,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '7',
                        'breed' => 'MC',
                        'age_wks' => '74.7',
                        'pro_date' => '26.05',
                        'received_egg' => 2000,
                        'commercial' => 0,
                        'broken' => 3,
                        'liquid' => 4,
                        'damage' => 2,
                        'total_reject' => 9,
                        'reject_percent' => 0.45,
                        'hatchable_egg' => 1991,
                        'total_hatchable' => 1991,
                        'set_egg_qty1' => 1991,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                ],
                'subtotal' => [
                    'received_egg' => 7920,
                    'commercial' => 0,
                    'broken' => 18,
                    'liquid' => 11,
                    'damage' => 19,
                    'total_reject' => 48,
                    'reject_percent' => 0.61,
                    'hatchable_egg' => 7872,
                    'total_hatchable' => 7872,
                    'set_egg_qty1' => 7872,
                    'set_date1' => '28.05.2025',
                    'set_egg_qty2' => 0,
                    'set_date2' => '',
                    'closing' => 0,
                ],
            ],
            [
                'shed_no' => '3',
                'flocks' => [
                    [
                        'flock_no' => '8',
                        'breed' => 'MC',
                        'age_wks' => '73.2',
                        'pro_date' => '27.05',
                        'received_egg' => 1950,
                        'commercial' => 0,
                        'broken' => 2,
                        'liquid' => 1,
                        'damage' => 1,
                        'total_reject' => 4,
                        'reject_percent' => 0.21,
                        'hatchable_egg' => 1946,
                        'total_hatchable' => 1946,
                        'set_egg_qty1' => 1946,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '9',
                        'breed' => 'MC',
                        'age_wks' => '72.8',
                        'pro_date' => '28.05',
                        'received_egg' => 1890,
                        'commercial' => 0,
                        'broken' => 3,
                        'liquid' => 1,
                        'damage' => 1,
                        'total_reject' => 5,
                        'reject_percent' => 0.26,
                        'hatchable_egg' => 1885,
                        'total_hatchable' => 1885,
                        'set_egg_qty1' => 1885,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '10',
                        'breed' => 'MC',
                        'age_wks' => '72.1',
                        'pro_date' => '29.05',
                        'received_egg' => 2400,
                        'commercial' => 0,
                        'broken' => 2,
                        'liquid' => 1,
                        'damage' => 1,
                        'total_reject' => 4,
                        'reject_percent' => 0.17,
                        'hatchable_egg' => 2396,
                        'total_hatchable' => 2396,
                        'set_egg_qty1' => 2396,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                ],
                'subtotal' => [
                    'received_egg' => 6240,
                    'commercial' => 0,
                    'broken' => 7,
                    'liquid' => 3,
                    'damage' => 3,
                    'total_reject' => 13,
                    'reject_percent' => 0.21,
                    'hatchable_egg' => 6227,
                    'total_hatchable' => 6227,
                    'set_egg_qty1' => 6227,
                    'set_date1' => '28.05.2025',
                    'set_egg_qty2' => 0,
                    'set_date2' => '',
                    'closing' => 0,
                ],
            ],
            [
                'shed_no' => '51.B',
                'flocks' => [
                    [
                        'flock_no' => '11',
                        'breed' => 'MC',
                        'age_wks' => '71.5',
                        'pro_date' => '30.05',
                        'received_egg' => 1850,
                        'commercial' => 0,
                        'broken' => 1,
                        'liquid' => 0,
                        'damage' => 0,
                        'total_reject' => 1,
                        'reject_percent' => 0.05,
                        'hatchable_egg' => 1849,
                        'total_hatchable' => 1849,
                        'set_egg_qty1' => 1849,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                ],
                'subtotal' => [
                    'received_egg' => 1850,
                    'commercial' => 0,
                    'broken' => 1,
                    'liquid' => 0,
                    'damage' => 0,
                    'total_reject' => 1,
                    'reject_percent' => 0.05,
                    'hatchable_egg' => 1849,
                    'total_hatchable' => 1849,
                    'set_egg_qty1' => 1849,
                    'set_date1' => '28.05.2025',
                    'set_egg_qty2' => 0,
                    'set_date2' => '',
                    'closing' => 0,
                ],
            ],
            [
                'shed_no' => '2',
                'flocks' => [
                    [
                        'flock_no' => '12',
                        'breed' => 'MC',
                        'age_wks' => '70.9',
                        'pro_date' => '31.05',
                        'received_egg' => 2200,
                        'commercial' => 0,
                        'broken' => 8,
                        'liquid' => 3,
                        'damage' => 4,
                        'total_reject' => 15,
                        'reject_percent' => 0.68,
                        'hatchable_egg' => 2185,
                        'total_hatchable' => 2185,
                        'set_egg_qty1' => 2185,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '13',
                        'breed' => 'MC',
                        'age_wks' => '70.2',
                        'pro_date' => '01.06',
                        'received_egg' => 2100,
                        'commercial' => 0,
                        'broken' => 6,
                        'liquid' => 2,
                        'damage' => 3,
                        'total_reject' => 11,
                        'reject_percent' => 0.52,
                        'hatchable_egg' => 2089,
                        'total_hatchable' => 2089,
                        'set_egg_qty1' => 2089,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '14',
                        'breed' => 'MC',
                        'age_wks' => '69.8',
                        'pro_date' => '02.06',
                        'received_egg' => 2000,
                        'commercial' => 0,
                        'broken' => 5,
                        'liquid' => 2,
                        'damage' => 2,
                        'total_reject' => 9,
                        'reject_percent' => 0.45,
                        'hatchable_egg' => 1991,
                        'total_hatchable' => 1991,
                        'set_egg_qty1' => 1991,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '15',
                        'breed' => 'MC',
                        'age_wks' => '69.1',
                        'pro_date' => '03.06',
                        'received_egg' => 1950,
                        'commercial' => 0,
                        'broken' => 4,
                        'liquid' => 1,
                        'damage' => 2,
                        'total_reject' => 7,
                        'reject_percent' => 0.36,
                        'hatchable_egg' => 1943,
                        'total_hatchable' => 1943,
                        'set_egg_qty1' => 1943,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '16',
                        'breed' => 'MC',
                        'age_wks' => '68.7',
                        'pro_date' => '04.06',
                        'received_egg' => 1900,
                        'commercial' => 0,
                        'broken' => 3,
                        'liquid' => 1,
                        'damage' => 1,
                        'total_reject' => 5,
                        'reject_percent' => 0.26,
                        'hatchable_egg' => 1895,
                        'total_hatchable' => 1895,
                        'set_egg_qty1' => 1895,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                    [
                        'flock_no' => '17',
                        'breed' => 'MC',
                        'age_wks' => '68.3',
                        'pro_date' => '05.06',
                        'received_egg' => 2090,
                        'commercial' => 0,
                        'broken' => 14,
                        'liquid' => 6,
                        'damage' => 8,
                        'total_reject' => 28,
                        'reject_percent' => 1.34,
                        'hatchable_egg' => 2062,
                        'total_hatchable' => 2062,
                        'set_egg_qty1' => 2062,
                        'set_date1' => '28.05.2025',
                        'set_egg_qty2' => 0,
                        'set_date2' => '',
                        'closing' => 0,
                        'remarks' => '',
                    ],
                ],
                'subtotal' => [
                    'received_egg' => 12240,
                    'commercial' => 0,
                    'broken' => 40,
                    'liquid' => 15,
                    'damage' => 20,
                    'total_reject' => 75,
                    'reject_percent' => 0.61,
                    'hatchable_egg' => 12165,
                    'total_hatchable' => 12165,
                    'set_egg_qty1' => 2640,
                    'set_date1' => '28.05.2025',
                    'set_egg_qty2' => 9525,
                    'set_date2' => '29.05.2025',
                    'closing' => 0,
                ],
            ],
        ];

        // Grand totals
        $grandTotal = [
            'received_egg' => 30000,
            'commercial' => 0,
            'broken' => 70,
            'liquid' => 30,
            'damage' => 44,
            'total_reject' => 144,
            'reject_percent' => 0.48,
            'hatchable_egg' => 29856,
            'total_hatchable' => 29856,
            'set_egg_qty1' => 20331,
            'set_date1' => '28.05.2025',
            'set_egg_qty2' => 9525,
            'set_date2' => '29.05.2025',
            'closing' => 0,
        ];

        return Inertia::render('report/egg-receive-and-grading-report', [
            'reportData' => $reportData,
            'sheds' => $sheds,
            'grandTotal' => $grandTotal,
        ]);
    }
}

